plugins {
    id 'java'
}

group = 'com.soulther.mod'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Basic setup
}

jar {
    manifest {
        attributes([
            "Specification-Title"     : "soulther",
            "Specification-Vendor"    : "Defender11 Team",
            "Implementation-Title"   : "Soulther",
            "Implementation-Version" : "1.0.0",
            "Implementation-Vendor"  : "Defender11 Team"
        ])
    }
}
