modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="soulther"
version="1.0.0"
displayName="Soulther: The Dark Dimension"
authors="Defender11 Team"
description='''
Warden hikayesinden esinlenilmiş ruh emme odaklı karanlık boyut modu!
'''
